// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import ExampleController from "./example_controller"
application.register("example", ExampleController)

import FormUploadController from "./form_upload_controller"
application.register("form-upload", FormUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)
